// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: tax.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaxRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CityId              int32                  `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	TripDurationSeconds int64                  `protobuf:"varint,2,opt,name=trip_duration_seconds,json=tripDurationSeconds,proto3" json:"trip_duration_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TaxRequest) Reset() {
	*x = TaxRequest{}
	mi := &file_tax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxRequest) ProtoMessage() {}

func (x *TaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxRequest.ProtoReflect.Descriptor instead.
func (*TaxRequest) Descriptor() ([]byte, []int) {
	return file_tax_proto_rawDescGZIP(), []int{0}
}

func (x *TaxRequest) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *TaxRequest) GetTripDurationSeconds() int64 {
	if x != nil {
		return x.TripDurationSeconds
	}
	return 0
}

type TaxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxAmount     float64                `protobuf:"fixed64,1,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	TaxRate       float64                `protobuf:"fixed64,2,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaxResponse) Reset() {
	*x = TaxResponse{}
	mi := &file_tax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxResponse) ProtoMessage() {}

func (x *TaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxResponse.ProtoReflect.Descriptor instead.
func (*TaxResponse) Descriptor() ([]byte, []int) {
	return file_tax_proto_rawDescGZIP(), []int{1}
}

func (x *TaxResponse) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *TaxResponse) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

var File_tax_proto protoreflect.FileDescriptor

const file_tax_proto_rawDesc = "" +
	"\n" +
	"\ttax.proto\x12\x03tax\"Y\n" +
	"\n" +
	"TaxRequest\x12\x17\n" +
	"\acity_id\x18\x01 \x01(\x05R\x06cityId\x122\n" +
	"\x15trip_duration_seconds\x18\x02 \x01(\x03R\x13tripDurationSeconds\"G\n" +
	"\vTaxResponse\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\x01 \x01(\x01R\ttaxAmount\x12\x19\n" +
	"\btax_rate\x18\x02 \x01(\x01R\ataxRate2C\n" +
	"\n" +
	"TaxService\x125\n" +
	"\x10CalculateTripTax\x12\x0f.tax.TaxRequest\x1a\x10.tax.TaxResponseB#Z!github.com/Kitten-King/tax_sdk/pbb\x06proto3"

var (
	file_tax_proto_rawDescOnce sync.Once
	file_tax_proto_rawDescData []byte
)

func file_tax_proto_rawDescGZIP() []byte {
	file_tax_proto_rawDescOnce.Do(func() {
		file_tax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tax_proto_rawDesc), len(file_tax_proto_rawDesc)))
	})
	return file_tax_proto_rawDescData
}

var file_tax_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tax_proto_goTypes = []any{
	(*TaxRequest)(nil),  // 0: tax.TaxRequest
	(*TaxResponse)(nil), // 1: tax.TaxResponse
}
var file_tax_proto_depIdxs = []int32{
	0, // 0: tax.TaxService.CalculateTripTax:input_type -> tax.TaxRequest
	1, // 1: tax.TaxService.CalculateTripTax:output_type -> tax.TaxResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tax_proto_init() }
func file_tax_proto_init() {
	if File_tax_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tax_proto_rawDesc), len(file_tax_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tax_proto_goTypes,
		DependencyIndexes: file_tax_proto_depIdxs,
		MessageInfos:      file_tax_proto_msgTypes,
	}.Build()
	File_tax_proto = out.File
	file_tax_proto_goTypes = nil
	file_tax_proto_depIdxs = nil
}
