// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: tax.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaxService_CalculateTripTax_FullMethodName = "/tax.TaxService/CalculateTripTax"
)

// TaxServiceClient is the client API for TaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxServiceClient interface {
	CalculateTripTax(ctx context.Context, in *TaxRequest, opts ...grpc.CallOption) (*TaxResponse, error)
}

type taxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxServiceClient(cc grpc.ClientConnInterface) TaxServiceClient {
	return &taxServiceClient{cc}
}

func (c *taxServiceClient) CalculateTripTax(ctx context.Context, in *TaxRequest, opts ...grpc.CallOption) (*TaxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxResponse)
	err := c.cc.Invoke(ctx, TaxService_CalculateTripTax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxServiceServer is the server API for TaxService service.
// All implementations must embed UnimplementedTaxServiceServer
// for forward compatibility.
type TaxServiceServer interface {
	CalculateTripTax(context.Context, *TaxRequest) (*TaxResponse, error)
	mustEmbedUnimplementedTaxServiceServer()
}

// UnimplementedTaxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaxServiceServer struct{}

func (UnimplementedTaxServiceServer) CalculateTripTax(context.Context, *TaxRequest) (*TaxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateTripTax not implemented")
}
func (UnimplementedTaxServiceServer) mustEmbedUnimplementedTaxServiceServer() {}
func (UnimplementedTaxServiceServer) testEmbeddedByValue()                    {}

// UnsafeTaxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxServiceServer will
// result in compilation errors.
type UnsafeTaxServiceServer interface {
	mustEmbedUnimplementedTaxServiceServer()
}

func RegisterTaxServiceServer(s grpc.ServiceRegistrar, srv TaxServiceServer) {
	// If the following call panics, it indicates UnimplementedTaxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaxService_ServiceDesc, srv)
}

func _TaxService_CalculateTripTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxServiceServer).CalculateTripTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxService_CalculateTripTax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxServiceServer).CalculateTripTax(ctx, req.(*TaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaxService_ServiceDesc is the grpc.ServiceDesc for TaxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tax.TaxService",
	HandlerType: (*TaxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateTripTax",
			Handler:    _TaxService_CalculateTripTax_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tax.proto",
}
